### ISSUE TITLE
Can't find Contra 

### ISSUE THREAD

**Issue by olivergiangvu** [gingerbeardman/alfred-moby-games#5]
Just try and the 1st. game come to my mind is Contra https://www.mobygames.com/game/4863/contra/

but it doesnt work for me - I'm on lastest 1.3 but also tried with Alfred Gallery 1.2
![CleanShot 2024-08-03 at 07 13 18](https://github.com/user-attachments/assets/72bf3b20-3366-470a-bd56-650810552ba0)

**Comment by gingerbeardman** [comment]
Thanks for the report!

The issue here is that there are so many matches the result search gets truncated and can no longer be parsed.

Reducing the max results from 30 to 25 solves it.

Fixed in https://github.com/gingerbeardman/alfred-moby-games/releases/tag/1.4

**Comment by olivergiangvu** [comment]
Thanks - let  me update the new one.

**Comment by gingerbeardman** [comment]
1.4 is on Gallery already
