### ISSUE TITLE
[REQ] add support for AlfredExtraPane

### ISSUE THREAD

**Issue by olivergiangvu** [gingerbeardman/alfred-moby-games#7]
Hi,

I think this will be wonderful enhancement if you can add the support of this HTML viewer https://github.com/mr-pennyworth/alfred-extra-pane

Thanks!

**Comment by gingerbeardman** [comment]
I'll happily accept a PR, but I don't think I'll be adding this myself as I have too much already on my todo list.

Thanks for your understanding!

**Comment by gingerbeardman** [comment]
OK, this was very easy to add so I'll release a new version soon!

We get Quick Look and AlfredExtrPane support — two birds with one stone.

Thanks for the suggestion @olivergiangvu

**Comment by gingerbeardman** [comment]
1.6 adds 
- support for Quick Look
- AlfredExtraPane

should be in gallery soon, or grab it from https://github.com/gingerbeardman/alfred-moby-games/releases/tag/1.6

**Comment by olivergiangvu** [comment]
Thank alot. I worked like charm now.
